### PR TITLE
Compat update for String rename

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by yuyichao** [comment]
This changes the return type and is potentially breaking.

**Comment by timholy** [comment]
Doesn't it just change spelling? On julia-0.4:
```jl
julia> using Compat; using Compat.String

julia> String
Union{ASCIIString,UTF8String}

julia> ByteString
Union{ASCIIString,UTF8String}
```

**Comment by yuyichao** [comment]
Ah, yeah, this one is fine, I think i might have misread the `ByteString` as `UTF8String`

**Comment by yuyichao** [comment]
AppVeyor failure seems to be unrelated. This requires `Compat 0.7.15`

**Comment by timholy** [comment]
Yes, the REQUIRE file should be updated.

**Comment by timholy** [comment]
That same AppVeyor error appears at https://github.com/JuliaIO/HDF5.jl/pull/302

**Pull request merged**
